### ISSUE TITLE
Install by composer does not work

### ISSUE THREAD

**Issue by jg-development** [Novalnet-AG/magento2-payment-integration-novalnet#2]
This is because this repo is not integrated in packagist.
And the name "novalnet/module-payment" is already in packagist by the oxid module.

Please rename the extension and add it to the packagist.

**Comment by Novalnet-Technic** [comment]
We have resolved the issue now. Right now we have updated the latest module in the packagist. Please try installing through the composer again, to install the magento 2 extension.
