### ISSUE TITLE
Novalnet Payment Module breaks Swagger

### ISSUE THREAD

**Issue by wilfriedwolf** [Novalnet-AG/magento2-payment-integration-novalnet#4]
Hi there,

I was trying to work with my shop and found that now your Module is installed I can not use Swagger anymore, since the definitions in your `\Novalnet\Payment\Api\NNRepositoryInterface` are presumably too vage (using "mixed" in the comments)?

Anyhow it throws an Exception while generating the Swagger definitions:

The "anyType" data type isn't declared. Verify the type and try again.

Best regards,

Willi

**Comment by Novalnet-Technic** [comment]
Hello @wilfriedwolf , 

Our technical department is evaluating the query. We will come up with updates shortly.

--
Regards,
Novalnet Team

**Comment by Novalnet-Technic** [comment]
Hello @wilfriedwolf , 

We have updated the module for the exception swagger and released a new version, 12.4.3. Hope this version release will resolve your query. 

Thanks! 

--
Regards,
Novalnet Team

**Comment by wilfriedwolf** [comment]
Hi @Novalnet-Technic,

unfortunately it does not. Basically you would need to replace the `@param mixed` and `@return mixed` statements with appropriate data structure objects, so the required structure could be determined by the swagger generator.

As I see it, this applies to 
* `\Novalnet\Payment\Api\NNRepositoryInterface::getRedirectURL`
* `\Novalnet\Payment\Api\NNRepositoryInterface::placeOrder`
* `\Novalnet\Payment\Api\NNRepositoryInterface::estimateShippingMethod`
* `\Novalnet\Payment\Api\NNRepositoryInterface::getProductPageParams`
* `\Novalnet\Payment\Api\NNRepositoryInterface::applyShippingMethod`

That fixed would solve the problem in my opinion

Best regards and thanks too..

Willi

**Comment by constancyGmbH** [comment]
I had the same Problem, but Version 13.0.0 fixes it for me. If you just need the swagger Documentation you can just change the "mixed" type in these files listed above to "string".

**Comment by Novalnet-Technic** [comment]
Hello everyone, 

We have updated the module for the exception swagger in version 13, this version release will resolved your query.

Best regards, 
Novalnet Team
